[build]
  command = "python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.8.12"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  PIP_VERSION = "23.0.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[context.production.environment]
  FLASK_ENV = "production"