[build]
  command = "npm install && npm run build"
  publish = "templates"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.11.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false