[build]
  command = "pip install -r requirements.txt && python main.py"
  publish = "templates"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  PIP_VERSION = "23.0.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[context.production.environment]
  FLASK_ENV = "production"